import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { Providers } from '@/redux/provider/provider'
import SignInPage from './SignIn/page'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'OmarBookRoot',
  description: 'Generated by create next app',
}

export default function RootLayout({ children}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  )
}
